server:
  port: 8080

spring:
  application:
    name: point-api

  datasource:
    url: jdbc:h2:mem:pointdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: point
    password: point1234

  jpa:
    hibernate:
      ddl-auto: none       # schema.sql을 쓸 거라 자동 DDL 생성 비활성화
    show-sql: true         # 개발용 SQL 로그
    properties:
      hibernate:
        format_sql: true   # SQL 포맷팅
        highlight_sql: true

  h2:
    console:
      enabled: true        # H2 콘솔 사용
      path: /h2-console

  sql:
    init:
      mode: always         # 애플리케이션 시작 시 schema.sql/data.sql 항상 실행
      encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
